#services:
#  test:
#    image: testapi:0725
#    build:
#      context: ./
#      dockerfile: Dockerfile
#
#    ports:
#      - "8093:8093"
#
#    networks:
#      - test
#
#  mariadb:
#    image: mariadb:11.0.2
#
#    ports:
#      - "3306:3306"
#    environment:
##      - MYSQL_USER=root
##      - MYSQL_PASSWORD=ray716898
#      - MYSQL_ROOT_PASSWORD=systex.6214
##      - MYSQL_DATABASE=DEMO
#    volumes:
#      - ./db/data:/var/lib/mysql
#      - ./db/initdb.d:/docker-entrypoint-initdb.d
#    networks:
#      - test
#
#  redis:
#    image: redis:7.0.12
#    container_name: my-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - /opt/homebrew/var/redis:/var/lib/redis
#    networks:
#      - test
#
#networks:
#  test:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.23.0.3/16



version: "3.7"
services:
  test:
    image: testapi
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - redis
  db:
    image: mariadb:11.0.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db-data:/var/lib/mysql
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
volumes:
  db-data:
